version: '3'

services:
  app:
    build: .
    container_name: employee-dep-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - employee-dep-service-logs:/logs
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: 'postgres:14-alpine'
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres  # TODO: Remove open secrets
      - POSTGRES_PASSWORD=postgres
    command:
      -c listen_addresses='*' # Updates postgresql.conf
    networks:
      - my-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  my-network:

volumes:
    employee-dep-service-logs:


