version: '3'

services:
  app:
    build: .
    container_name: employee-dep-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - employee-dep-service-logs:/logs
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: 'postgres:14-alpine'
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres  # TODO: Remove open secrets
      - POSTGRES_PASSWORD=postgres
    command:
      -c listen_addresses='*' # Updates postgresql.conf
    networks:
      - my-network

networks:
  my-network:

volumes:
    employee-dep-service-logs:


