package org.ibs.middleware.messaging;

import org.ibs.domain.entity.Person;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.rest.core.annotation.*;
import org.springframework.stereotype.Component;

// Event handlers to customize Person Controller generated by Spring Data REST.
// Note: WebMvcConfigurer and Interceptor DOESN'T work with Spring Data REST (https://github.com/spring-projects/spring-data-rest/issues/1522)
@Component
@RepositoryEventHandler()
public class PersonEventHandler {

    @Autowired
    private PersonMessageProducer messageProducer;

    @HandleBeforeCreate
    public void handlePersonSave(Person p) {
        messageProducer.sendAddedPerson(p);
    }

    @HandleBeforeDelete
    public void handlePersonDelete(Person p) {
        messageProducer.sendDeletedPerson(p);
    }

    @HandleBeforeSave
    public void handlePersonUpdate(Person p) {
        messageProducer.sendUpdatedPerson(p);
    }
}
